name: text_only
version: 0.0.1
description: Material Design Lite 'MDL Text-Only Template'
author: <Mike Mitterer> <office@mikemitterer.at>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  mdl: # '>=2.1.0 <3.0.0'
    git:
      url: git@github.com:MikeMitterer/dart-material-design-lite.git
      ref: v2.2
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'

#  sass_var_transformer:
#    path: ../..

dev_dependencies:
  sass_builder: ^1.0.0

#transformers:
#  - sass_var_transformer:
#      # Converts @mdl to ../.pub-cache/hosted/pub.dartlang.org/mdl-x.xx.x/lib
#      mdl: package:mdl
#      text_only: package:text_only